### ISSUE TITLE
Errors on Windows

### ISSUE THREAD

**Issue by alexwebbb** [btholt/complete-intro-to-react#74]
As far as I can tell, this project does not run on windows, even when doing the tutorial step by step. I get an astronomical number of errors when running es lint (3024). Given that I have run plenty of other react projects on windows, this is pretty lame. Guess i will be running the create react app instead, what a let down.

A small portion of the result of running webpack

```
 @ ./js/Search.jsx 16:16-37
 @ ./js/App.jsx
 @ ./js/ClientApp.jsx
 @ multi ./js/ClientApp.jsx ./js/ClientApp.js ./public/bundle.js

ERROR in ./js/Header.jsx

C:\Users\alexw\Source\complete-intro-to-react\js\Header.jsx
  8:22  error  Parsing error: Unexpected token :

✖ 1 problem (1 error, 0 warnings)

 @ ./js/Search.jsx 20:14-33
 @ ./js/App.jsx
 @ ./js/ClientApp.jsx
 @ multi ./js/ClientApp.jsx ./js/ClientApp.js ./public/bundle.js

ERROR in ./js/reducers.js

C:\Users\alexw\Source\complete-intro-to-react\js\reducers.js
  6:39  error  Parsing error: Unexpected token :

✖ 1 problem (1 error, 0 warnings)

 @ ./js/store.js 17:16-37
 @ ./js/App.jsx
 @ ./js/ClientApp.jsx
 @ multi ./js/ClientApp.jsx ./js/ClientApp.js ./public/bundle.js

C:\Users\alexw\Source\complete-intro-to-react>
```

**Comment by gpspake** [comment]
When you see those unexpected token errors, it's often because babel isn't loading the correct plugins or they're being loaded in the correct order. It seems to me that, for some reason the "env" preset that loads the es2015 plugin isn't ever being loaded on Windows. I still haven't been able to figure out how it's working elsewhere.

**Comment by alexwebbb** [comment]
I see!

Here is the webpack.config.dev.js from the create react app. I also have the production one, but it is quite long
```

'use strict';

const autoprefixer = require('autoprefixer');
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');
const InterpolateHtmlPlugin = require('react-dev-utils/InterpolateHtmlPlugin');
const WatchMissingNodeModulesPlugin = require('react-dev-utils/WatchMissingNodeModulesPlugin');
const eslintFormatter = require('react-dev-utils/eslintFormatter');
const ModuleScopePlugin = require('react-dev-utils/ModuleScopePlugin');
const getClientEnvironment = require('./env');
const paths = require('./paths');

// Webpack uses `publicPath` to determine where the app is being served from.
// In development, we always serve from the root. This makes config easier.
const publicPath = '/';
// `publicUrl` is just like `publicPath`, but we will provide it to our app
// as %PUBLIC_URL% in `index.html` and `process.env.PUBLIC_URL` in JavaScript.
// Omit trailing slash as %PUBLIC_PATH%/xyz looks better than %PUBLIC_PATH%xyz.
const publicUrl = '';
// Get environment variables to inject into our app.
const env = getClientEnvironment(publicUrl);

// This is the development configuration.
// It is focused on developer experience and fast rebuilds.
// The production configuration is different and lives in a separate file.
module.exports = {
  // You may want 'eval' instead if you prefer to see the compiled output in DevTools.
  // See the discussion in https://github.com/facebookincubator/create-react-app/issues/343.
  devtool: 'cheap-module-source-map',
  // These are the "entry points" to our application.
  // This means they will be the "root" imports that are included in JS bundle.
  // The first two entry points enable "hot" CSS and auto-refreshes for JS.
  entry: [
    // Include an alternative client for WebpackDevServer. A client's job is to
    // connect to WebpackDevServer by a socket and get notified about changes.
    // When you save a file, the client will either apply hot updates (in case
    // of CSS changes), or refresh the page (in case of JS changes). When you
    // make a syntax error, this client will display a syntax error overlay.
    // Note: instead of the default WebpackDevServer client, we use a custom one
    // to bring better experience for Create React App users. You can replace
    // the line below with these two lines if you prefer the stock client:
    // require.resolve('webpack-dev-server/client') + '?/',
    // require.resolve('webpack/hot/dev-server'),
    require.resolve('react-dev-utils/webpackHotDevClient'),
    // We ship a few polyfills by default:
    require.resolve('./polyfills'),
    // Errors should be considered fatal in development
    require.resolve('react-error-overlay'),
    // Finally, this is your app's code:
    paths.appIndexJs,
    // We include the app code last so that if there is a runtime error during
    // initialization, it doesn't blow up the WebpackDevServer client, and
    // changing JS code would still trigger a refresh.
  ],
  output: {
    // Next line is not used in dev but WebpackDevServer crashes without it:
    path: paths.appBuild,
    // Add /* filename */ comments to generated require()s in the output.
    pathinfo: true,
    // This does not produce a real file. It's just the virtual path that is
    // served by WebpackDevServer in development. This is the JS bundle
    // containing code from all our entry points, and the Webpack runtime.
    filename: 'static/js/bundle.js',
    // There are also additional JS chunk files if you use code splitting.
    chunkFilename: 'static/js/[name].chunk.js',
    // This is the URL that app is served from. We use "/" in development.
    publicPath: publicPath,
    // Point sourcemap entries to original disk location (format as URL on Windows)
    devtoolModuleFilenameTemplate: info =>
      path.resolve(info.absoluteResourcePath).replace(/\\/g, '/'),
  },
  resolve: {
    // This allows you to set a fallback for where Webpack should look for modules.
    // We placed these paths second because we want `node_modules` to "win"
    // if there are any conflicts. This matches Node resolution mechanism.
    // https://github.com/facebookincubator/create-react-app/issues/253
    modules: ['node_modules', paths.appNodeModules].concat(
      // It is guaranteed to exist because we tweak it in `env.js`
      process.env.NODE_PATH.split(path.delimiter).filter(Boolean)
    ),
    // These are the reasonable defaults supported by the Node ecosystem.
    // We also include JSX as a common component filename extension to support
    // some tools, although we do not recommend using it, see:
    // https://github.com/facebookincubator/create-react-app/issues/290
    // `web` extension prefixes have been added for better support
    // for React Native Web.
    extensions: ['.web.js', '.js', '.json', '.web.jsx', '.jsx'],
    alias: {
      
      // Support React Native Web
      // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
      'react-native': 'react-native-web',
    },
    plugins: [
      // Prevents users from importing files from outside of src/ (or node_modules/).
      // This often causes confusion because we only process files within src/ with babel.
      // To fix this, we prevent you from importing files out of src/ -- if you'd like to,
      // please link the files into your node_modules/ and let module-resolution kick in.
      // Make sure your source files are compiled, as they will not be processed in any way.
      new ModuleScopePlugin(paths.appSrc),
    ],
  },
  module: {
    strictExportPresence: true,
    rules: [
      // TODO: Disable require.ensure as it's not a standard language feature.
      // We are waiting for https://github.com/facebookincubator/create-react-app/issues/2176.
      // { parser: { requireEnsure: false } },

      // First, run the linter.
      // It's important to do this before Babel processes the JS.
      {
        test: /\.(js|jsx)$/,
        enforce: 'pre',
        use: [
          {
            options: {
              formatter: eslintFormatter,
              
            },
            loader: require.resolve('eslint-loader'),
          },
        ],
        include: paths.appSrc,
      },
      // ** ADDING/UPDATING LOADERS **
      // The "file" loader handles all assets unless explicitly excluded.
      // The `exclude` list *must* be updated with every change to loader extensions.
      // When adding a new loader, you must add its `test`
      // as a new entry in the `exclude` list for "file" loader.

      // "file" loader makes sure those assets get served by WebpackDevServer.
      // When you `import` an asset, you get its (virtual) filename.
      // In production, they would get copied to the `build` folder.
      {
        exclude: [
          /\.html$/,
          /\.(js|jsx)$/,
          /\.css$/,
          /\.json$/,
          /\.bmp$/,
          /\.gif$/,
          /\.jpe?g$/,
          /\.png$/,
        ],
        loader: require.resolve('file-loader'),
        options: {
          name: 'static/media/[name].[hash:8].[ext]',
        },
      },
      // "url" loader works like "file" loader except that it embeds assets
      // smaller than specified limit in bytes as data URLs to avoid requests.
      // A missing `test` is equivalent to a match.
      {
        test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
        loader: require.resolve('url-loader'),
        options: {
          limit: 10000,
          name: 'static/media/[name].[hash:8].[ext]',
        },
      },
      // Process JS with Babel.
      {
        test: /\.(js|jsx)$/,
        include: paths.appSrc,
        loader: require.resolve('babel-loader'),
        options: {
          
          // This is a feature of `babel-loader` for webpack (not Babel itself).
          // It enables caching results in ./node_modules/.cache/babel-loader/
          // directory for faster rebuilds.
          cacheDirectory: true,
        },
      },
      // "postcss" loader applies autoprefixer to our CSS.
      // "css" loader resolves paths in CSS and adds assets as dependencies.
      // "style" loader turns CSS into JS modules that inject <style> tags.
      // In production, we use a plugin to extract that CSS to a file, but
      // in development "style" loader enables hot editing of CSS.
      {
        test: /\.css$/,
        use: [
          require.resolve('style-loader'),
          {
            loader: require.resolve('css-loader'),
            options: {
              importLoaders: 1,
            },
          },
          {
            loader: require.resolve('postcss-loader'),
            options: {
              // Necessary for external CSS imports to work
              // https://github.com/facebookincubator/create-react-app/issues/2677
              ident: 'postcss',
              plugins: () => [
                require('postcss-flexbugs-fixes'),
                autoprefixer({
                  browsers: [
                    '>1%',
                    'last 4 versions',
                    'Firefox ESR',
                    'not ie < 9', // React doesn't support IE8 anyway
                  ],
                  flexbox: 'no-2009',
                }),
              ],
            },
          },
        ],
      },
      // ** STOP ** Are you adding a new loader?
      // Remember to add the new extension(s) to the "file" loader exclusion list.
    ],
  },
  plugins: [
    // Makes some environment variables available in index.html.
    // The public URL is available as %PUBLIC_URL% in index.html, e.g.:
    // <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
    // In development, this will be an empty string.
    new InterpolateHtmlPlugin(env.raw),
    // Generates an `index.html` file with the <script> injected.
    new HtmlWebpackPlugin({
      inject: true,
      template: paths.appHtml,
    }),
    // Add module names to factory functions so they appear in browser profiler.
    new webpack.NamedModulesPlugin(),
    // Makes some environment variables available to the JS code, for example:
    // if (process.env.NODE_ENV === 'development') { ... }. See `./env.js`.
    new webpack.DefinePlugin(env.stringified),
    // This is necessary to emit hot updates (currently CSS only):
    new webpack.HotModuleReplacementPlugin(),
    // Watcher doesn't work well if you mistype casing in a path so we use
    // a plugin that prints an error when you attempt to do this.
    // See https://github.com/facebookincubator/create-react-app/issues/240
    new CaseSensitivePathsPlugin(),
    // If you require a missing module and then `npm install` it, you still have
    // to restart the development server for Webpack to discover it. This plugin
    // makes the discovery automatic so you don't have to restart.
    // See https://github.com/facebookincubator/create-react-app/issues/186
    new WatchMissingNodeModulesPlugin(paths.appNodeModules),
    // Moment.js is an extremely popular library that bundles large locale files
    // by default due to how Webpack interprets its code. This is a practical
    // solution that requires the user to opt into importing specific locales.
    // https://github.com/jmblog/how-to-optimize-momentjs-with-webpack
    // You can remove this if you don't use Moment.js:
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
  ],
  // Some libraries import Node modules but don't use them in the browser.
  // Tell Webpack to provide empty mocks for them so importing them works.
  node: {
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
  },
  // Turn off performance hints during development because we don't do any
  // splitting or minification in interest of speed. These warnings become
  // cumbersome.
  performance: {
    hints: false,
  },
};



```

**Comment by alexwebbb** [comment]
I ended up continuing this course by running it in a create-react-app project. Everything works if you just be sure to export an App component at some point

**Comment by alexwebbb** [comment]
extremely puzzled to find "//" comments in the css file

**Comment by ghughes27** [comment]
Also have been having problems with ESLint using Windows, however receiving mostly no-undef errors.  Using Atom IDE.  Currently at Code-Splitting section, but the errors have been similar pretty much through the course...

/*===========
YARN DEV REPORT
============*/
yarn dev v0.27.5
$ webpack-dev-server
Project is running at http://localhost:8080/
webpack output is served from /public/
404s will fallback to /index.html
Hash: 1d8ce7067066a2879af6
Version: webpack 2.6.1
Time: 19960ms
      Asset     Size  Chunks                    Chunk Names
0.bundle.js  10.9 kB       0  [emitted]
  bundle.js  5.58 MB       1  [emitted]  [big]  main
chunk    {0} 0.bundle.js 3.55 kB {1} [rendered]
 [./js/Landing.jsx] ./js/Landing.jsx 3.55 kB {0} [built] [1 error]
chunk    {1} bundle.js (main) 1.95 MB [entry] [rendered]
 [./js/App.jsx] ./js/App.jsx 2.4 kB {1} [built]
 [./js/ClientApp.jsx] ./js/ClientApp.jsx 643 bytes {1} [built]
 [./node_modules/react-dom/index.js] ./~/react-dom/index.js 164 bytes {1} [built]
 [./node_modules/react-hot-loader/patch.js] ./~/react-hot-loader/patch.js 146 bytes {1} [built]
 [./node_modules/react-router-dom/es/index.js] ./~/react-router-dom/es/index.js 1.03 kB {1} [built]
 [./node_modules/react/react.js] ./~/react/react.js 161 bytes {1} [built]
 [./node_modules/strip-ansi/index.js] ./~/strip-ansi/index.js 403 bytes {1} [built]
 [./node_modules/url/url.js] ./~/url/url.js 25.9 kB {1} [built]
 [./node_modules/webpack-dev-server/client/index.js?http:/localhost:8080] (webpack)-dev-server/client?http://localhost:8080 8.77 kB {1} [built]
 [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.41 kB {1} [built]
 [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 2.06 kB {1} [built]
 [./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 180 bytes {1} [built] [./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.1 kB {1} [built]
    [0] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./js/ClientApp.jsx 88 bytes {1} [built]
 [./node_modules/webpack/hot/only-dev-server.js] (webpack)/hot/only-dev-server.js 2.81 kB {1} [built]
     + 529 hidden modules

ERROR in ./js/Details.jsx

C:\Users\usr\Desktop\complete-intro-to-react\js\Details.jsx
  15:3  error  'props' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)

 @ ./js/App.jsx 10:0-32
 @ ./js/ClientApp.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./js/ClientApp.jsx

ERROR in ./js/AsyncRoute.jsx

C:\Users\usr\Desktop\complete-intro-to-react\js\AsyncRoute.jsx
   7:3  error  'state' is not defined      no-undef
  16:3  error  'props' is not defined      no-undef
  20:3  error  'component' is not defined  no-undef

✖ 3 problems (3 errors, 0 warnings)

 @ ./js/App.jsx 8:0-38
 @ ./js/ClientApp.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./js/ClientApp.jsx

ERROR in ./js/Landing.jsx

C:\Users\usr\Desktop\complete-intro-to-react\js\Landing.jsx
  10:3  error  'props' is not defined       no-undef
  15:3  error  'goToSearch' is not defined  no-undef

✖ 2 problems (2 errors, 0 warnings)

 @ ./js/App.jsx 34:26-46
 @ ./js/ClientApp.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./js/ClientApp.jsx

ERROR in ./js/ShowCard.jsx

C:\Users\usr\Desktop\complete-intro-to-react\js\ShowCard.jsx
  28:3  error  'props' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)

 @ ./js/Search.jsx 5:0-34
 @ ./js/App.jsx
 @ ./js/ClientApp.jsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./js/ClientApp.jsx
webpack: Failed to compile.

/*===========
YARN LINT REPORT:
============*/
yarn lint v0.27.5
$ eslint **/*.{js,jsx} --quiet
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at hasTypeOfOperator (C:\Users\gphug\Desktop\complete-intro-to-react\node_modules\eslint\lib\rules\no-undef.js:19:18)
    at Program:exit.globalScope.through.forEach.ref (C:\Users\gphug\Desktop\complete-intro-to-react\node_modules\eslint\lib\rules\no-undef.js:58:44)
    at Array.forEach (native)
    at EventEmitter.Program:exit (C:\Users\gphug\Desktop\complete-intro-to-react\node_modules\eslint\lib\rules\no-undef.js:55:37)
    at emitOne (events.js:120:20)
    at EventEmitter.emit (events.js:210:7)
    at NodeEventGenerator.applySelector (C:\Users\gphug\Desktop\complete-intro-to-react\node_modules\eslint\lib\util\node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (C:\Users\gphug\Desktop\complete-intro-to-react\node_modules\eslint\lib\util\node-event-generator.js:294:22)
    at NodeEventGenerator.leaveNode (C:\Users\gphug\Desktop\complete-intro-to-react\node_modules\eslint\lib\util\node-event-generator.js:317:14)
    at CodePathAnalyzer.leaveNode (C:\Users\gphug\Desktop\complete-intro-to-react\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:622:23)
    at CommentEventGenerator.leaveNode (C:\Users\gphug\Desktop\complete-intro-to-react\node_modules\eslint\lib\util\comment-event-generator.js:111:23)
    at Traverser.leave (C:\Users\gphug\Desktop\complete-intro-to-react\node_modules\eslint\lib\eslint.js:932:36)
error Command failed with exit code 1.

- P.S. thanks again for the course!!
